#########################
#     ArathothIII       #
#     by.ColdRain       #
#########################

# 数据库设置
database:
  host: localhost
  port: 3306
  user: root
  password: root
  database: test
  table:
    correction-player: arathoth_correction_player
    correction-timed: arathoth_correction_timed

settings:
  # lore相关功能配置
  lore:
    # 是否启用 (不启用可以提升性能)
    enable: false
    # 物品绑定Pattern
    bind:
      pattern: 'Owner: [VALUE]'
      auto-bind:
        # 在玩家拿到手后会把物品中匹配这个pattern的一行lore中的%player%替换为玩家名
        pattern: 'Owner: %player%'
        # 启用listener
        listener:
          # 捡起
          pick: true
          # 容器/背包中点击
          click: true
          # 交互
          interact: true
  # 状态板设置
  status:
    # 玩家打开状态版的命令
    command: 'statusinfo'
    # 使用该指令的权限 (不写就没有)
    perm: ''
    message:
      # 是否隐藏值为0的属性
      # 一旦启用，会隐藏含有这个值为0的属性的一行
      hideZero: true
      # 最小行数, 少于此行数将会执行noStatusAction
      minLines: 2
      noStatusAction: |-
        send color *"&c你没有属性"
      # 内容，活用papi变量
      # 高版本支持TabooLib的牛逼颜色代码
      text:
        - '&7&l>&m--------&8&l[ &f%player_name% &8&l]&7&l&m--------&7&l<'
        - '   &7&l> &7物理伤害: &f%arathoth_damage:total%'
  script:
    # javaScript Building, 在此注册的静态类/object可以被javascript调用
    js-building:
      Bukkit: 'org.bukkit.Bukkit'